# Generated by Django 4.2.7 on 2023-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('description', models.TextField(max_length=100, verbose_name='카테고리 설명')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
